name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build-test-and-dockerize:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build backend (Maven)
        run: ./mvnw -B package -DskipTests || mvn -B package -DskipTests

      - name: Run backend tests
        run: ./mvnw test || mvn test

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install frontend dependencies
        run: cd frontend && (yarn install --frozen-lockfile || npm install)

      - name: Build frontend
        run: cd frontend && (yarn build || npm run build)

      - name: Run frontend tests
        run: cd frontend && (yarn test || npm test || echo "No frontend tests found")

      - name: Build backend Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/eni-backend:staging .

      - name: Build frontend Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/eni-frontend:staging ./frontend

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push backend Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/eni-backend:staging

      - name: Push frontend Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/eni-frontend:staging